### ISSUE TITLE
bug maybe or something

### ISSUE THREAD

**Issue by BatmanGamingYT** [ekoerp1/eaglercraft-1.15-Final-Release#5]
reason? 
![Screenshot 2023-05-17 10 01 25 PM](https://github.com/ekoerp1/eaglercraft-1.15-Final-Release/assets/92596501/ca9e446c-2321-45b2-89e0-dd513f11e7e4)
![Screenshot 2023-05-17 9 58 15 PM](https://github.com/ekoerp1/eaglercraft-1.15-Final-Release/assets/92596501/d2b1a855-12ce-43be-b6a7-870977af5fcd)

**Comment by drippy-cat** [comment]
Are you using this through a fork? Can you provide more information? Thanks!

**Comment by BatmanGamingYT** [comment]
no fork

**Comment by drippy-cat** [comment]
What computer are you running this on? What version of chrome are you running? Which client are you using? [Client One](https://g.deev.is/eaglercraft/) [Client Two](https://ekoerp1.github.io/eaglercraft-1.15-Final-Release/javascript/) or the [Offline Client](https://github.com/lax1dude/eaglercraft/raw/main/stable-download/Offline_Download_Version.html). Please provide more information and describe how to replicate this issue. 

```
Chrome Version:
Eaglercaft Client
How to replicate the issue:
```

**Comment by BatmanGamingYT** [comment]
chromebook
version 112.0.5615.134

**Comment by BatmanGamingYT** [comment]
client two
112.0.5615.134 version
chromebook
btw this like only happens if i create a new world and other exist worlds are like gone

**Comment by drippy-cat** [comment]
I can't seem to replicate this issue. Try looking at [this](https://www.reddit.com/r/eaglercraft/comments/11t4iyw/vfshandlevs_was_null/) reddit post. What country are you in? It's possible that Eaglercraft doesn't work outside the US.

**Comment by drippy-cat** [comment]
Are you in India by any chance?

**Comment by drippy-cat** [comment]
Be sure no to use [your fork](https://github.com/BatmanGamingYT/eaglercraft-1.15-Final-Release) of this repo (as it is one commit ahead which can affect the program).

**Comment by BatmanGamingYT** [comment]
i live in the us

**Comment by drippy-cat** [comment]
Why does your time zone say 8hrs behind (EST)
![image](https://github.com/ekoerp1/eaglercraft-1.15-Final-Release/assets/95929812/af3623e3-2ebb-4865-9b95-8a750c3d90e2)

**Comment by drippy-cat** [comment]
I can't seem to find the problem. There also doesn't appear to be a `VFSHandle.vfs` file in this repo.

**Comment by drippy-cat** [comment]
I tried to replicate the issue but I didn't encounter any problems. I think it's something on your end.

**Comment by BatmanGamingYT** [comment]
yeah probally i think its on my end

**Comment by BatmanGamingYT** [comment]
on mines it says we have same time
![Screenshot 2023-05-18 8 41 06 PM](https://github.com/ekoerp1/eaglercraft-1.15-Final-Release/assets/92596501/2843281c-a5de-48e6-9125-199bc7824f9f)

**Comment by drippy-cat** [comment]
Hmm interesting.
