### ISSUE TITLE
The repository is not original

### ISSUE THREAD

**Issue by CiroDOS** [ekoerp1/eaglercraft-1.15-Final-Release#6]
Because you modified the README.md file the eaglercraft repository is automatically invalid
![image](https://github.com/ekoerp1/eaglercraft-1.15-Final-Release/assets/129799906/1e2b4767-e220-4a26-9eac-d48ca546ca46)

**Comment by drippy-cat** [comment]
What do you mean? This is the original eaglercraft repository.

**Comment by CiroDOS** [comment]
Even if the repository is original, if you modify a file you would be invalidating the SHA-256 of this. That's what I mean.

**Comment by ekoerp1** [comment]
Yes this is true as it is a backup I added backup links because the original didn’t work
